name: PHPStan
on: pull_request

jobs:
  phpstan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.1', '8.2']

    name: phpstan check php${{ matrix.php-versions }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up php
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Install dependencies
        run: composer i

      - name: Run coding standards check
        run: composer phpstan
